# DigitalOcean DOKS Cluster Configuration
# Auto-generated by monobase-infra provision wizard.
# Replicates the medicard-shape values/cluster/ layout but targets DOKS
# (mycure's production cluster runs on DigitalOcean Kubernetes).

terraform {
  required_version = ">= 1.6"

  # Backend left local until the team migrates state to a remote backend
  # (DigitalOcean Spaces or otherwise). When migrating, swap with:
  #   backend "s3" { bucket = "mycure-tfstate"; key = "cluster/doks.tfstate"; ... }
  backend "local" {}

  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.0"
    }
  }
}

provider "digitalocean" {
  # Reads DIGITALOCEAN_TOKEN from environment
}

module "doks_cluster" {
  source = "../../terraform/modules/do-doks"

  cluster_name       = var.cluster_name
  region             = var.region
  kubernetes_version = var.kubernetes_version

  deployment_profile = var.deployment_profile
  node_size          = var.node_size
  node_count         = var.node_count
  min_nodes          = var.min_nodes
  max_nodes          = var.max_nodes

  auto_upgrade     = var.auto_upgrade
  surge_upgrade    = var.surge_upgrade
  ha_control_plane = var.ha_control_plane

  vpc_cidr = var.vpc_cidr
  tags     = var.tags

  maintenance_window_day  = var.maintenance_window_day
  maintenance_window_hour = var.maintenance_window_hour
}
