{{- if and .Values.enabled .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "hapihub.fullname" . }}-secrets
  namespace: {{ include "hapihub.namespace" . }}
  labels:
    {{- include "hapihub.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore | default (printf "%s-secretstore" (include "hapihub.namespace" .)) }}
    kind: {{ .Values.externalSecrets.secretStoreKind | default "SecretStore" }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  target:
    name: {{ include "hapihub.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.secrets }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        {{- if .property }}
        property: {{ .property }}
        {{- end }}
    {{- end }}
{{- end }}
