{{- if and .Values.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hapihub.fullname" . }}
  namespace: {{ include "hapihub.namespace" . }}
  labels:
    {{- include "hapihub.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hapihub.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
      {{- if .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- end }}
{{- end }}
