# Gateway System Namespace
# Created by Envoy Gateway operator, but declaring here for clarity
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "gateway.namespace" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
