{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-repo-credentials
  namespace: {{ .Values.namespace | default "velero" }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore | default "gcp-secretstore" }}
    kind: ClusterSecretStore
  target:
    name: velero-repo-credentials
    creationPolicy: Owner
  data:
    - secretKey: repository-password
      remoteRef:
        key: {{ .Values.externalSecrets.repoCredentialsKey | default "monobase-velero-repo-password" }}
{{- end }}
