# mise (formerly rtx) - Development Tools Configuration
# https://mise.jdx.dev/
#
# Install all tools: mise install
# Update tools: mise upgrade

[tools]
# Kubernetes Tools
kubectl = "latest"
helm = "latest"
argocd = "latest"

# Terraform
terraform = "latest"

# Shell Utilities
fzf = "latest"        # Fuzzy finder for interactive selections

# Cloud CLIs for Secret Management
# Using cloud KMS providers (GCP by default, AWS/Azure optional)
gcloud = "latest"     # GCP Secret Manager (default provider)
# aws-cli = "latest"  # Uncomment for AWS Secrets Manager
# azure-cli = "latest"  # Uncomment for Azure Key Vault
