# SOPS Configuration
# Defines encryption rules for secrets
# https://github.com/getsops/sops

# Creation rules - define which keys to use for new files
creation_rules:
  # Encrypt all .enc.yaml files with age
  - path_regex: \.enc\.yaml$
    age: >-
      age17j6tzuf4q5pxv9c2p7786cdv6puqsw3xmmsjm9p9ee6hm4pw9gasqem40y
    # Only encrypt the 'data' and 'stringData' fields in Kubernetes secrets
    # Leave metadata and structure visible
    encrypted_regex: '^(data|stringData)$'

  # Encrypt all .enc.json files with age
  - path_regex: \.enc\.json$
    age: >-
      age17j6tzuf4q5pxv9c2p7786cdv6puqsw3xmmsjm9p9ee6hm4pw9gasqem40y

  # Encrypt specific secret files
  - path_regex: secrets/.*\.yaml$
    age: >-
      age17j6tzuf4q5pxv9c2p7786cdv6puqsw3xmmsjm9p9ee6hm4pw9gasqem40y
    encrypted_regex: '^(data|stringData|password|token|key|secret)$'

# Note: age17j6tzuf4q5pxv9c2p7786cdv6puqsw3xmmsjm9p9ee6hm4pw9gasqem40y will be replaced by scripts/secrets.sh
# with your actual age public key (e.g., age1ql3z7hjy54pw3hyww5ayyfg7...)
