{{- if .Values.account.enabled }}
# ArgoCD Application: Monobase Account Frontend
# Sync Wave 3 - Deploy application after database

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.namespace }}-account
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    path: charts/account
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision | default "main" }}
    helm:
      releaseName: account
      valuesObject:
        global: {{ .Values.global | toYaml | nindent 8 }}
        replicaCount: {{ .Values.account.replicaCount | default 2 }}
        image: {{ .Values.account.image | toYaml | nindent 10 }}
        resources: {{ .Values.account.resources | toYaml | nindent 10 }}
        {{- if .Values.account.gateway }}
        gateway: {{ .Values.account.gateway | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.account.podDisruptionBudget }}
        podDisruptionBudget: {{ .Values.account.podDisruptionBudget | toYaml | nindent 10 }}
        {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m
{{- end }}
