# ArgoCD Application: Database Secrets
# Deploys ExternalSecrets for database credentials (PostgreSQL, MongoDB, MinIO)
# Sync Wave 1 - Deploy secrets before databases

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.namespace }}-database-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: database-secrets
    app.kubernetes.io/component: external-secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision }}
    path: charts/database-secrets
    helm:
      releaseName: database-secrets
      valuesObject:
        global:
          namespace: {{ .Values.global.namespace }}
          domain: {{ .Values.global.domain }}
          environment: {{ .Values.global.environment }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespace }}

  syncPolicy:
    automated:
      prune: true       # Remove ExternalSecrets when disabled
      selfHeal: true    # Auto-correct configuration drift
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m

  # Ignore expected differences
  ignoreDifferences:
    # ExternalSecret fields auto-populated by ESO operator
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.target.deletionPolicy
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
