{{- if index .Values "dentalemon-myaccount" }}
{{- if (index .Values "dentalemon-myaccount").enabled }}
# ArgoCD Application: DentaLemon MyAccount Frontend
# Sync Wave 3 - Deploy application after database

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.namespace }}-dentalemon-myaccount
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    path: charts/dentalemon-myaccount
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision | default "main" }}
    helm:
      releaseName: dentalemon-myaccount
      valuesObject:
        {{- toYaml (index .Values "dentalemon-myaccount") | nindent 8 }}
        global: {{ .Values.global | toYaml | nindent 10 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m
{{- end }}
{{- end }}
