{{- if .Values.externalDNS.enabled }}
# ArgoCD Application: External DNS (Automatic DNS Record Management)
# Sync Wave 1 - Deploy with infrastructure before applications need DNS

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.namespace }}-external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    # Use our custom multi-instance External DNS chart
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision }}
    path: charts/external-dns
    helm:
      releaseName: external-dns
      # Pass entire externalDNS config from deployment values
      valuesObject:
        enabled: {{ .Values.externalDNS.enabled }}

        {{- with .Values.externalDNS.image }}
        image:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with .Values.externalDNS.global }}
        global:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with .Values.externalDNS.instances }}
        instances:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with .Values.externalDNS.podAnnotations }}
        podAnnotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with .Values.externalDNS.podLabels }}
        podLabels:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with .Values.externalDNS.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with .Values.externalDNS.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with .Values.externalDNS.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with .Values.externalDNS.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with .Values.externalDNS.priorityClassName }}
        priorityClassName: {{ . }}
        {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m
{{- end }}
