{{- if .Values.minio.enabled }}
# ArgoCD Application: MinIO Object Storage
# Sync Wave 2 - Deploy storage before applications

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.namespace }}-minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: minio
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.x.x
    helm:
      releaseName: minio
      valuesObject:
        image:
          repository: {{ .Values.minio.image.repository | default "bitnamilegacy/minio" }}
          tag: {{ .Values.minio.image.tag | default "2025.7.23-debian-12-r3" }}
        mode: {{ .Values.minio.mode | default "standalone" }}
        statefulset:
          replicaCount: {{ .Values.minio.statefulset.replicaCount | default 1 }}
        auth:
          rootUser: {{ .Values.minio.auth.rootUser | default "minioadmin" }}
          rootPassword: {{ .Values.minio.auth.rootPassword | default "minioadmin" }}
        persistence:
          enabled: {{ .Values.minio.persistence.enabled | default true }}
          storageClass: {{ .Values.minio.persistence.storageClass | default "" }}
          size: {{ .Values.minio.persistence.size | default "10Gi" }}
        resources:
          requests:
            cpu: {{ .Values.minio.resources.requests.cpu | default "100m" }}
            memory: {{ .Values.minio.resources.requests.memory | default "256Mi" }}
          limits:
            cpu: {{ .Values.minio.resources.limits.cpu | default "500m" }}
            memory: {{ .Values.minio.resources.limits.memory | default "512Mi" }}
        defaultBuckets: {{ .Values.minio.defaultBuckets | default "monobase-files" }}
        podSecurityContext:
          enabled: true
          fsGroup: 1001
          fsGroupChangePolicy: "OnRootMismatch"
        containerSecurityContext:
          enabled: true
          runAsUser: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m
        factor: 2
{{- end }}
