{{- if .Values.minio.enabled }}
# ArgoCD Application: MinIO (Object Storage)
# Sync Wave 2 - Deploy storage before applications

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.namespace }}-minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: minio
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 17.x.x
    helm:
      releaseName: minio
      valuesObject:
        {{- toYaml .Values.minio | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m
{{- end }}
