{{- if .Values.minio.enabled }}
# ArgoCD Application: MinIO Object Storage (Wrapper Chart)
# Sync Wave 2 - Deploy storage before applications
# Uses local wrapper chart which includes Bitnami MinIO + HTTPRoute

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.namespace }}-minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: {{ .Values.argocd.repoURL }}
    path: charts/minio
    targetRevision: {{ .Values.argocd.targetRevision | default "main" }}
    helm:
      releaseName: minio
      valuesObject:
        enabled: true
        
        # Global values for namespace and domain
        global:
          namespace: {{ .Values.global.namespace }}
          domain: {{ .Values.global.domain }}
          gateway:
            name: {{ .Values.global.gateway.name }}
            namespace: {{ .Values.global.gateway.namespace }}
        
        # Pass through all MinIO configuration from deployment values
        {{- toYaml .Values.minio | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m
        factor: 2
{{- end }}
