{{- if .Values.minio.enabled }}
# ArgoCD Application: MinIO (Object Storage)
# Sync Wave 2 - Deploy storage before applications
# Uses local wrapper chart that includes official MinIO chart + Gateway HTTPRoute

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.namespace }}-minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision | default "main" }}
    path: charts/minio
    helm:
      releaseName: minio
      valuesObject:
        global:
          {{- toYaml .Values.global | nindent 10 }}
        {{- toYaml .Values.minio | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m
{{- end }}
