{{- if .Values.mongodb.enabled }}
# ArgoCD Application: MongoDB Database
# Sync Wave 2 - Deploy database before applications

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.namespace }}-mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: mongodb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.x.x
    helm:
      releaseName: mongodb
      valuesObject:
        image:
          repository: {{ .Values.mongodb.image.repository | default "bitnamilegacy/mongodb" }}
          tag: {{ .Values.mongodb.image.tag | default "8.0.4-debian-12-r0" }}
        auth:
          rootUser: {{ .Values.mongodb.auth.rootUser | default "root" }}
        architecture: replicaset
        replicaCount: {{ .Values.mongodb.replicaCount | default 1 }}
        persistence:
          enabled: {{ .Values.mongodb.persistence.enabled | default true }}
          storageClass: {{ .Values.mongodb.persistence.storageClass | default "" }}
          size: {{ .Values.mongodb.persistence.size | default "20Gi" }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m
{{- end }}
