{{- if .Values.mycurev8.enabled }}
# ArgoCD Application: MyCure v8 Frontend (Legacy)
# Sync Wave 3 - Deploy application after database

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.namespace }}-mycurev8
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    path: charts/mycurev8
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision | default "main" }}
    helm:
      releaseName: mycurev8
      valuesObject:
        {{- toYaml .Values.mycurev8 | nindent 8 }}
        global: {{ .Values.global | toYaml | nindent 10 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m
{{- end }}
