{{- if .Values.valkey.enabled }}
# ArgoCD Application: Valkey (Redis Cache)
# Sync Wave 2 - Deploy cache before applications

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.namespace }}-valkey
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: valkey
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 2.x.x
    helm:
      releaseName: valkey
      valuesObject:
        architecture: {{ .Values.valkey.architecture | default "standalone" }}
        master:
          persistence:
            enabled: {{ .Values.valkey.master.persistence.enabled | default false }}
            storageClass: {{ .Values.valkey.master.persistence.storageClass | default "" }}
            size: {{ .Values.valkey.master.persistence.size | default "8Gi" }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m
{{- end }}
