apiVersion: v2
name: mycure-pxp
description: MyCure PXP App (mycure satellite) - patient-facing web app
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - frontend
  - react
  - vite
  - pxp
  - patient
home: https://github.com/monobaselabs/monobase-infra
sources:
  - https://github.com/monobaselabs/monobase
maintainers:
  - name: Your Organization
    email: devops@example.com
