# Default values for HapiHub chart
# This is a YAML-formatted file with sensible defaults
# Override these values in deployments/{env}/values.yaml

# Global configuration (shared across charts)
global:
  domain: example.com
  namespace: example-prod
  environment: production
  gateway:
    name: shared-gateway
    namespace: gateway-system

# HapiHub application configuration
enabled: true

replicaCount: 2

image:
  repository: ghcr.io/mycurelabs/hapihub
  pullPolicy: IfNotPresent
  tag: "10.0.13"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

service:
  type: ClusterIP
  port: 7500
  targetPort: 7500
  annotations: {}

# Gateway API HTTPRoute configuration
gateway:
  enabled: true
  hostname: ""  # Empty = uses hapihub.{global.domain}
  parentRefs:
    - name: shared-gateway
      namespace: gateway-system

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 4Gi

livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 7500
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 7500
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 2

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 1

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - hapihub
          topologyKey: kubernetes.io/hostname

# Application configuration (ConfigMap)
config:
  # NOTE: PORT removed - causes known issue in HapiHub (port: NaN error)
  # App automatically uses default port 7500
  CLUSTER_INSTANCES: "max"
  RUN_WORKERS: "true"
  STORAGE_TYPE: "gfs"  # or "s3" for MinIO
  DB_SKIP_CREATE_INDEXES: "false"
  DB_RECREATE_INDEX_ON_CONFLICT: "false"

# External Secrets configuration
externalSecrets:
  enabled: false
  secretStore: ""
  refreshInterval: 1h
  secrets: []

# MongoDB dependency configuration (deployed separately)
mongodb:
  enabled: true
  # Service name - points to separate MongoDB release
  serviceName: "mongodb"
  database: "hapihub"
  replicaSet: "rs0"
  auth:
    enabled: false
    existingSecret: ""

# Service Monitor for Prometheus (if monitoring enabled)
serviceMonitor:
  enabled: false
  interval: 30s
  path: /metrics
