# GCP Secret Manager ClusterSecretStore
# Provides access to secrets stored in Google Cloud Secret Manager
# Authentication: Service Account Key (works with any Kubernetes cluster)

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secretstore
  labels:
    app.kubernetes.io/name: gcp-secretstore
    app.kubernetes.io/component: external-secrets
spec:
  provider:
    gcpsm:
      projectID: "mc-v4-prod"
      
      # Authentication using Service Account Key
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: secret-access-credentials
            namespace: external-secrets-system
