# PostgreSQL ExternalSecret
# Syncs PostgreSQL credentials from GCP Secret Manager to Kubernetes
# Used by: postgresql chart (Bitnami), API

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: mycure-staging
  labels:
    app.kubernetes.io/name: postgresql-credentials
    app.kubernetes.io/component: external-secrets
spec:
  # Refresh interval - how often to sync from GCP
  refreshInterval: 1h
  
  # Reference to ClusterSecretStore
  secretStoreRef:
    name: gcp-secretstore
    kind: ClusterSecretStore
  
  # Target Kubernetes secret
  target:
    name: postgresql
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # PostgreSQL postgres user password - required by Bitnami PostgreSQL chart
        postgres-password: "{{ .postgresPassword }}"
  
  # Data to fetch from GCP Secret Manager
  data:
    - secretKey: postgresPassword
      remoteRef:
        key: mycure-staging-postgresql-postgres-password
