# SOPS ClusterSecretStore
# Used when provider=sops
# For Git-encrypted secrets (age or PGP)

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: sops-secretstore
  labels:
    app.kubernetes.io/name: sops-secretstore
    app.kubernetes.io/component: external-secrets
    app.kubernetes.io/managed-by: argocd
spec:
  provider:
    sops:
      type: age  # or pgp
      secretRef:
        name: sops-age-key
        namespace: cert-manager  # Bootstrap secret location
        key: age.agekey
