apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secretstore
    kind: ClusterSecretStore
  target:
    name: velero-credentials
    creationPolicy: Owner
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .spacesAccessKey }}
          aws_secret_access_key={{ .spacesSecretKey }}
  data:
    - secretKey: spacesAccessKey
      remoteRef:
        key: monobase-digitalocean-spaces
        property: access_key
    - secretKey: spacesSecretKey
      remoteRef:
        key: monobase-digitalocean-spaces
        property: secret_key
