{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hapihub-docs.fullname" . }}
  namespace: {{ include "hapihub-docs.namespace" . }}
  labels:
    {{- include "hapihub-docs.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "hapihub-docs.selectorLabels" . | nindent 4 }}
{{- end }}
