{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "syncd.fullname" . }}
  namespace: {{ include "syncd.namespace" . }}
  labels:
    {{- include "syncd.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "syncd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "syncd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "syncd.serviceAccountName" . }}
      # Disable service environment variables to avoid port config conflicts
      enableServiceLinks: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          {{- if .Values.livenessProbe.httpGet }}
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path }}
            port: {{ .Values.livenessProbe.httpGet.port | default "http" }}
          {{- end }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          {{- if .Values.readinessProbe.httpGet }}
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.readinessProbe.httpGet.port | default "http" }}
          {{- end }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
        # Set HOME to /tmp to avoid permission denied errors when running as non-root
        - name: HOME
          value: "/tmp"
        # Load from ConfigMap (conditionally)
        {{- if .Values.config.NODE_ENV }}
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: {{ include "syncd.fullname" . }}
              key: NODE_ENV
        {{- end }}
        {{- if .Values.config.LOG_LEVEL }}
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: {{ include "syncd.fullname" . }}
              key: LOG_LEVEL
        {{- end }}
        # Port configuration - must be numeric (unquoted) for proper parsing
        - name: SYNCD_PORT
          value: {{ .Values.service.targetPort | quote }}
        - name: PORT
          value: {{ .Values.service.targetPort | quote }}
        # MongoDB connection - individual components
        # Note: MongoDB may be deployed separately in GitOps
        - name: MONGODB_HOST
          value: {{ include "syncd.mongodb.host" . | quote }}
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_DATABASE
          value: {{ include "syncd.mongodb.database" . | quote }}
        - name: MONGODB_USER
          value: {{ include "syncd.mongodb.username" . | quote }}
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-root-password
        # MONGO_URI constructed from components using K8s variable expansion
        - name: MONGO_URI
          value: "mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@$(MONGODB_HOST):$(MONGODB_PORT)/$(MONGODB_DATABASE)?replicaSet={{ .Values.mongodb.replicaSet }}&directConnection=true&authSource=admin"
        # Service URLs from dependencies
        {{- if .Values.valkey.enabled }}
        - name: REDIS_URL
          value: {{ include "syncd.valkey.url" . | quote }}
        {{- end }}
        {{- if .Values.mailpit.enabled }}
        - name: SMTP_HOST
          value: {{ include "syncd.mailpit.host" . | quote }}
        - name: SMTP_PORT
          value: "25"
        - name: SMTP_SECURE
          value: "false"
        {{- end }}
        # Load non-DB secrets from External Secrets Operator
        {{- if .Values.externalSecrets.enabled }}
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "syncd.fullname" . }}-secrets
              key: JWT_SECRET
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "syncd.fullname" . }}-secrets
              key: S3_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "syncd.fullname" . }}-secrets
              key: S3_SECRET_ACCESS_KEY
        {{- end }}
        # Additional environment variables from config
        {{- range $key, $value := .Values.config }}
        {{- if not (has $key (list "NODE_ENV" "LOG_LEVEL" "PORT")) }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
