{{- if and .Values.enabled .Values.networkPolicy (default false .Values.networkPolicy.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "syncd.fullname" . }}
  namespace: {{ include "syncd.namespace" . }}
  labels:
    {{- include "syncd.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "syncd.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }}
