{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncd.fullname" . }}
  namespace: {{ include "syncd.namespace" . }}
  labels:
    {{- include "syncd.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "syncd.selectorLabels" . | nindent 4 }}
{{- end }}
