apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:L+HEC+eM+t5GcAdcVlx7Ji7c+GBD8dtrkFhGY+0zmBMPHhPQIRbGaA==,iv:I42RMiOKbyIeRcNWcnALSaRMNhAUTChRAOMfeB53CPI=,tag:6bAysDYV/+GMuzqTBNHu8A==,type:str]
sops:
    age:
        - recipient: age17j6tzuf4q5pxv9c2p7786cdv6puqsw3xmmsjm9p9ee6hm4pw9gasqem40y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMGxzUWhiTVJqQXFPWDFH
            eEowUHFHOExtamRCSndIZ1NlMUhiWjVFelhZCkt6UTQ2Y3lqNUxKbzVtazRFOWRY
            UjRYWE81YW5tdThNNk5UL0ZsVzdzdjQKLS0tIHRGWlVORXhycDdwaHFJZEJYZU1Z
            TTdMYnR1K3llY1ZlRUJwOU5nQzRRK1UKnjcDr3fy5wv6DlZEA6xKHke++ulzehHA
            XD1eHucW8ijHlkamHXRfo8lCvi1JNXHodEcITU9+6cZO0zhJPbaV7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-18T03:27:37Z"
    mac: ENC[AES256_GCM,data:5AVOjKs0mSoeBtHoRpGijsKwWj5QJ0FeFkl7QaEQ4huqkcL2eUqpTJQg+ddBvBH7WTIBdgP2kn3Vlv32BJfnU/okrdJ1iiGObDndLFSE68D9GVg4o5lTP8HJKZ1Vfo+dZHYTV8DierCuNtuUEUi3YxaPvE5dnvPMjCP5TdDg+HA=,iv:7vKCfyxkTIKtxPBKR9qirDWfmq0ATdlZe1KvuLXsG4U=,tag:/JmEs5g4/8xPRvI4sdfuiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
