# External Secret for Cloudflare API Token
# Syncs from GCP Secret Manager to Kubernetes Secret

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cloudflare-token
    app.kubernetes.io/component: tls
spec:
  # Refresh interval
  refreshInterval: 1h
  
  # Reference to ClusterSecretStore
  secretStoreRef:
    name: gcp-secretstore
    kind: ClusterSecretStore
  
  # Target Kubernetes secret
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  
  # Data mapping
  data:
    - secretKey: api-token
      remoteRef:
        key: infrastructure-cloudflare-api-token
