# External Secret for MyCure Cloudflare API Token
# Syncs from GCP Secret Manager to Kubernetes Secret
# Used by letsencrypt-mycure-cloudflare-* ClusterIssuers

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mycure-cloudflare-api-token
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: mycure-cloudflare-token
    app.kubernetes.io/component: tls
    app.kubernetes.io/part-of: cert-manager-issuers
spec:
  # Refresh interval
  refreshInterval: 1h
  
  # Reference to ClusterSecretStore
  secretStoreRef:
    name: gcp-secretstore
    kind: ClusterSecretStore
  
  # Target Kubernetes secret
  target:
    name: mycure-cloudflare-api-token
    creationPolicy: Owner
  
  # Data mapping
  data:
    - secretKey: api-token
      remoteRef:
        key: infrastructure-cloudflare-api-token
