# Let's Encrypt Staging ClusterIssuer
# Use for testing to avoid rate limits
# Certificates from staging are NOT trusted by browsers

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app.kubernetes.io/name: letsencrypt-staging
    app.kubernetes.io/component: tls
    app.kubernetes.io/managed-by: argocd
spec:
  acme:
    # Let's Encrypt Staging Server
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    # Email for Let's Encrypt notifications (expiry, etc.)
    # This is templated and replaced by scripts/secrets.sh
    email: "{{ LETSENCRYPT_EMAIL }}"

    # Secret to store ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging-account-key

    # DNS-01 challenge solver (required for wildcard certificates)
    solvers:
      - dns01:
          cloudflare:
            # Cloudflare API token from Kubernetes secret
            # Created by External Secrets Operator
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
        selector:
          dnsZones:
            - "{{ DNS_ZONE }}"  # Templated by scripts/secrets.sh
