# ExternalSecret for Cloudflare API Token
# Syncs encrypted secret from chosen provider to Kubernetes Secret
# Used by cert-manager ClusterIssuers for DNS-01 challenge

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cloudflare-api-token
    app.kubernetes.io/component: tls
    app.kubernetes.io/managed-by: argocd
spec:
  # Refresh interval - check for secret updates
  refreshInterval: 1h

  # Reference to SecretStore (configured per provider)
  # Provider is set in infrastructure/values.yaml: externalSecrets.provider
  secretStoreRef:
    # SOPS: sops-secretstore
    # AWS: aws-secretstore
    # Azure: azure-secretstore
    # GCP: gcp-secretstore
    name: "{{ SECRET_STORE_NAME }}"  # Templated by scripts/secrets.sh
    kind: ClusterSecretStore

  # Target Kubernetes Secret
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Key name expected by cert-manager
        api-token: "{{ .cloudflare_api_token }}"

  # Source data (provider-specific)
  data:
    # The key name varies by provider:
    # SOPS: Reference to ConfigMap with encrypted data
    # AWS/Azure/GCP: Reference to cloud secret by name/path
    - secretKey: cloudflare_api_token
      remoteRef:
        # This will be set by scripts/secrets.sh based on provider
        key: "{{ SECRET_KEY }}"  # Provider-specific secret identifier
