# Default values for MinIO chart
# This is a YAML-formatted file with sensible defaults
# Override these values in deployment-specific values files

# Global configuration (shared across charts)
global:
  domain: example.com
  namespace: example-prod
  environment: production
  gateway:
    name: shared-gateway
    namespace: gateway-system

enabled: false  # Master enable/disable for both MinIO and HTTPRoute

nameOverride: ""
fullnameOverride: ""

# ===== Bitnami MinIO Chart Values (passed to subchart) =====
# These values are passed through to the Bitnami MinIO Helm chart dependency
# See https://github.com/bitnami/charts/tree/main/bitnami/minio for all options

# Image configuration
image:
  repository: bitnamilegacy/minio
  tag: "2025.7.23-debian-12-r3"

# Deployment mode
mode: standalone

# StatefulSet configuration
statefulset:
  replicaCount: 1

# Authentication
auth:
  rootUser: minioadmin
  rootPassword: minioadmin

persistence:
  enabled: true
  storageClass: longhorn
  size: 250Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Bucket configuration for Bitnami MinIO chart
defaultBuckets: "monobase-files"

# Security contexts for restricted PodSecurity standards
# Bitnami chart uses podSecurityContext and containerSecurityContext
podSecurityContext:
  enabled: true
  fsGroup: 1001
  fsGroupChangePolicy: "OnRootMismatch"
  supplementalGroups: []
  sysctls: []

containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

# ===== Custom Gateway API Configuration =====
# HTTPRoute configuration for exposing MinIO via Envoy Gateway

gateway:
  enabled: true
  hostname: ""  # Empty = uses storage.{global.domain}
  parentRefs:
    - name: shared-gateway
      namespace: gateway-system
  
  # Rate limiting configuration for MinIO traffic
  rateLimit:
    enabled: true
    # Per-IP download rate limit
    perIP:
      requests: 100
      unit: Second
    # Burst limit
    burst:
      requests: 1000
      unit: Minute
