{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ include "api.namespace" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          {{- if .Values.livenessProbe.httpGet }}
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path }}
            port: {{ .Values.livenessProbe.httpGet.port | default "http" }}
          {{- end }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          {{- if .Values.readinessProbe.httpGet }}
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.readinessProbe.httpGet.port | default "http" }}
          {{- end }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
        # Set HOME to /tmp to avoid permission denied errors when running as non-root
        - name: HOME
          value: "/tmp"
        # Load from ConfigMap
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: {{ include "api.fullname" . }}
              key: NODE_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: {{ include "api.fullname" . }}
              key: LOG_LEVEL
        - name: PORT
          value: "7213"
        # PostgreSQL connection - individual components
        # Note: PostgreSQL may be deployed separately in GitOps
        - name: POSTGRESQL_HOST
          value: {{ include "api.postgresql.host" . | quote }}
        - name: POSTGRESQL_PORT
          value: "5432"
        - name: POSTGRESQL_DATABASE
          value: {{ include "api.postgresql.database" . | quote }}
        - name: POSTGRESQL_USER
          value: {{ include "api.postgresql.username" . | quote }}
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: postgres-password
        # DATABASE_URL constructed from components using K8s variable expansion
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRESQL_USER):$(POSTGRESQL_PASSWORD)@$(POSTGRESQL_HOST):$(POSTGRESQL_PORT)/$(POSTGRESQL_DATABASE)"
        # Service URLs from dependencies
        {{- if .Values.valkey.enabled }}
        - name: REDIS_URL
          value: {{ include "api.valkey.url" . | quote }}
        {{- end }}
        {{- if .Values.minio.enabled }}
        - name: STORAGE_PROVIDER
          value: "minio"
        - name: STORAGE_ENDPOINT
          value: {{ include "api.minio.url" . | quote }}
        - name: STORAGE_PUBLIC_ENDPOINT
          value: {{ include "api.minio.url" . | quote }}
        - name: STORAGE_BUCKET
          value: {{ (index .Values.minio.buckets 0).name | default "monobase-files" | quote }}
        - name: STORAGE_REGION
          value: {{ .Values.minio.region | default "us-east-1" | quote }}
        - name: STORAGE_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio
              key: root-user
        - name: STORAGE_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: root-password
        - name: STORAGE_UPLOAD_URL_EXPIRY
          value: "300"
        - name: STORAGE_DOWNLOAD_URL_EXPIRY
          value: "900"
        {{- end }}
        {{- if .Values.mailpit.enabled }}
        - name: SMTP_HOST
          value: {{ include "api.mailpit.host" . | quote }}
        - name: SMTP_PORT
          value: "25"
        - name: SMTP_SECURE
          value: "false"
        {{- end }}
        # Load non-DB secrets from External Secrets Operator
        {{- if .Values.externalSecrets.enabled }}
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "api.fullname" . }}-secrets
              key: JWT_SECRET
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "api.fullname" . }}-secrets
              key: S3_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "api.fullname" . }}-secrets
              key: S3_SECRET_ACCESS_KEY
        {{- end }}
        # Additional environment variables from config
        {{- range $key, $value := .Values.config }}
        {{- if not (has $key (list "NODE_ENV" "LOG_LEVEL" "PORT")) }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
      {{- $nodePool := include "api.nodePool" . -}}
      {{- if or $nodePool .Values.nodeSelector }}
      nodeSelector:
        {{- if $nodePool }}
        node-pool: {{ $nodePool }}
        {{- end }}
        {{- with .Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or $nodePool .Values.tolerations }}
      tolerations:
        {{- if $nodePool }}
        - key: "node-pool"
          operator: "Equal"
          value: {{ $nodePool | quote }}
          effect: "NoSchedule"
        {{- end }}
        {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
{{- end }}
