{{- if and .Values.enabled .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ include "api.namespace" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ include "api.gateway.name" . }}
      namespace: {{ include "api.gateway.namespace" . }}
      sectionName: https  # Only attach to HTTPS listener
      {{- if .Values.gateway.sectionName }}
      # Override: {{ .Values.gateway.sectionName }}
      {{- end }}
  hostnames:
    - {{ include "api.gateway.hostname" . }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "api.fullname" . }}
          port: {{ .Values.service.port }}
          weight: 1
      {{- if .Values.gateway.filters }}
      filters:
        {{- toYaml .Values.gateway.filters | nindent 8 }}
      {{- end }}
{{- end }}
