apiVersion: v2
name: mycure
description: MyCure - Patient-facing healthcare application
type: application
version: 1.0.0
appVersion: "10.0.22"
keywords:
  - mycure
  - frontend
  - vue
  - healthcare
home: https://github.com/monobaselabs/monobase-infra
sources:
  - https://github.com/monobaselabs/monobase
maintainers:
  - name: Your Organization
    email: devops@example.com
