{{- if .Values.enabled }}
{{- if gt (len .Values.instances) 0 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "external-dns.fullname" . }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
rules:
# Read Gateway resources cluster-wide (needed for cross-namespace Gateway references)
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways", "httproutes", "tcproutes", "tlsroutes"]
  verbs: ["get", "list", "watch"]

# Read Services cluster-wide (needed to get LoadBalancer IPs from Gateway)
- apiGroups: [""]
  resources: ["services", "endpoints", "pods", "nodes"]
  verbs: ["get", "list", "watch"]

# Read EndpointSlices cluster-wide (needed for endpoint discovery)
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch"]

# Read Namespaces cluster-wide (needed for Gateway API sources in namespaced mode)
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
{{- end }}
{{- end }}
