{{- if .Values.enabled }}
{{- range .Values.instances }}
{{- if .enabled }}
{{- $instance := . }}
{{- $root := $ }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "external-dns.serviceAccountName" (dict "instance" $instance "root" $root) }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "external-dns.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $instance.name }}
  {{- with $instance.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
