# MyCure Production Infrastructure Configuration
# DigitalOcean Kubernetes (DOKS) - Production Environment
# Domain: mycureapp.com

# EnvoyProxy Configuration - Static IP for DigitalOcean DOKS
envoyProxyConfig:
  enabled: true
  cloudProvider: digitalocean

  digitalocean:
    # LoadBalancer will auto-provision
    # Note: For true static IP with DigitalOcean, use FLIPOP operator
    # See: docs/infrastructure/static-ip-digitalocean.md
    loadBalancerId: ""  # Auto-provision
    loadBalancerName: ""  # Auto-provision

# Gateway configuration
gateway:
  domain: mycureapp.com

  # Gateway configuration
  gateway:
    name: shared-gateway
    namespace: gateway-system
    gatewayClassName: envoy-gateway
    listeners:
      https:
        enabled: true
        port: 443
        protocol: HTTPS
      http:
        enabled: true
        port: 80
        protocol: HTTP

  # TLS/Certificate configuration
  tls:
    enabled: true
    secretName: gateway-tls
    certManager:
      enabled: true
      clusterIssuer: letsencrypt-prod
      includeApex: true  # Include apex domain for production
      # Specific subdomains for production environment
      subdomains:
        - ""  # mycureapp.com (apex domain)

  # HTTP to HTTPS redirect
  httpRedirect:
    enabled: true
    statusCode: 301
