# PhilCare Staging Infrastructure Configuration
# Azure AKS Cluster - Staging Environment
# Domain: stg.mycure.stitchtechsolutions.com

# EnvoyProxy Configuration - Static IP for Azure AKS
envoyProxyConfig:
  enabled: true
  cloudProvider: azure

  azure:
    # Public IP Name (recommended method)
    # TODO: Replace with actual Azure public IP name after creating static IP
    # See: docs/infrastructure/static-ip-azure.md
    publicIpName: "philcare-staging-gateway-ip"

    # Node Resource Group (MC_* resource group)
    # TODO: Replace with actual node resource group from: az aks show --query nodeResourceGroup
    resourceGroup: "MC_philcare-staging-rg_philcare-staging-aks_eastus"

    # Alternative: Use direct IP address (less preferred)
    # ipv4Address: "135.171.153.160"

# Gateway configuration
gateway:
  domain: stg.mycure.stitchtechsolutions.com

  # Gateway  configuration
  gateway:
    name: shared-gateway
    namespace: gateway-system
    gatewayClassName: envoy-gateway
    listeners:
      https:
        enabled: true
        port: 443
        protocol: HTTPS
      http:
        enabled: true
        port: 80
        protocol: HTTP

  # TLS/Certificate configuration
  tls:
    enabled: true
    secretName: gateway-tls
    certManager:
      enabled: true
      clusterIssuer: letsencrypt-prod
      includeApex: false  # No apex domain for staging
      # Specific subdomains for staging environment
      subdomains:
        - ""  # stg.mycure.stitchtechsolutions.com (no subdomain prefix needed)

  # HTTP to HTTPS redirect
  httpRedirect:
    enabled: true
    statusCode: 301
