apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: {{ .Values.namespace }}
spec:
  selector: { app: ollama-egress }
  ports:
    - { name: ollama, port: {{ .Values.port }}, targetPort: {{ .Values.port }}, protocol: TCP }
