{{- if .Values.envoyGateway.enabled }}
# ArgoCD Application: Envoy Gateway
# Sync Wave 0 - Deploy gateway infrastructure (cluster-wide)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    chart: gateway-helm
    repoURL: oci://docker.io/envoyproxy/gateway-helm
    targetRevision: {{ .Values.envoyGateway.version | default "v1.2.0" }}
    helm:
      releaseName: envoy-gateway
      skipCrds: false  # Install Gateway API CRDs (required for fresh clusters)
      valuesObject:
        config:
          envoyGateway:
            extensionApis:
              enableEnvoyPatchPolicy: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
{{- end }}
