{{- if .Values.externalDNS.enabled }}
# ArgoCD Application: external-dns
# Sync Wave 1 - Deploy DNS automation after Gateway (depends on Gateway API CRDs)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: charts/external-dns
    helm:
      releaseName: external-dns
      valueFiles:
        - ../../infrastructure/external-dns/values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
{{- end }}
