{{- if .Values.externalSecrets.enabled }}
# ArgoCD Application: External Secrets SecretStores
# Deploys SecretStore/ClusterSecretStore resources after External Secrets Operator is ready
# Sync Wave 1 - Deployed after External Secrets Operator (wave 0)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-stores
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # After external-secrets operator
  labels:
    app.kubernetes.io/name: external-secrets-stores
    app.kubernetes.io/component: infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision }}
    path: infrastructure/external-secrets

    # Use directory with Helm-style templates
    directory:
      recurse: false
      # Pass values for templating
      helm:
        releaseName: external-secrets-stores
        values: |
          externalSecrets:
            provider: {{ .Values.externalSecrets.provider | default "aws" | quote }}
            {{- if eq .Values.externalSecrets.provider "aws" }}
            aws:
              region: {{ .Values.externalSecrets.aws.region | default "us-east-1" | quote }}
              roleArn: {{ .Values.externalSecrets.aws.roleArn | default "" | quote }}
              serviceAccountName: {{ .Values.externalSecrets.aws.serviceAccountName | default "external-secrets-sa" | quote }}
            {{- end }}
            {{- if eq .Values.externalSecrets.provider "azure" }}
            azure:
              vaultUrl: {{ .Values.externalSecrets.azure.vaultUrl | default "" | quote }}
              identityId: {{ .Values.externalSecrets.azure.identityId | default "" | quote }}
            {{- end }}
            {{- if eq .Values.externalSecrets.provider "gcp" }}
            gcp:
              projectId: {{ .Values.externalSecrets.gcp.projectId | default "" | quote }}
              region: {{ .Values.externalSecrets.gcp.region | default "us-central1" | quote }}
              clusterName: {{ .Values.externalSecrets.gcp.clusterName | default "" | quote }}
              serviceAccountEmail: {{ .Values.externalSecrets.gcp.serviceAccountEmail | default "" | quote }}
            {{- end }}
  
  destination:
    server: https://kubernetes.default.svc
    # ClusterSecretStore is cluster-scoped, but ServiceAccount goes to external-secrets-system
  
  syncPolicy:
    automated:
      prune: true       # Remove SecretStores if provider changes
      selfHeal: true    # Auto-correct configuration drift
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  
  # Ignore expected differences
  ignoreDifferences:
    # SecretStore status is managed by controller
    - group: external-secrets.io
      kind: ClusterSecretStore
      jsonPointers:
        - /status
    - group: external-secrets.io
      kind: SecretStore
      jsonPointers:
        - /status
{{- end }}
