{{- if .Values.envoyGateway.enabled }}
# ArgoCD Application: Gateway Resources
# Deploys the shared Gateway resource after Envoy Gateway operator is ready
# Sync Wave 1 - Deployed after Envoy Gateway operator (wave 0)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # After envoy-gateway operator
  labels:
    app.kubernetes.io/name: gateway-resources
    app.kubernetes.io/component: infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision }}
    path: charts/gateway
    helm:
      releaseName: gateway
      valuesObject:
        {{- toYaml .Values.gateway | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-system
  
  syncPolicy:
    automated:
      prune: true       # Remove resources if removed from Git
      selfHeal: true    # Auto-correct configuration drift
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Better for CRDs
      - RespectIgnoreDifferences=true  # Respect ignoreDifferences during sync
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  
  # Ignore expected differences
  ignoreDifferences:
    # Gateway status is managed by controller
    - group: gateway.networking.k8s.io
      kind: Gateway
      jsonPointers:
        - /status
        - /spec/listeners/0/tls/certificateRefs  # Ignore K8s auto-added group field
    # HTTPRoute status is managed by controller
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /status
        - /spec/parentRefs  # Ignore K8s auto-added group/kind fields
        - /spec/rules/0/matches  # Ignore auto-added default matches
    # Certificate status is managed by cert-manager
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /status
    # GatewayClass is managed by Envoy Gateway operator, not this application
    - group: gateway.networking.k8s.io
      kind: GatewayClass
      jqPathExpressions:
        - .
{{- end }}
