{{- if .Values.monitoring.grafana.enabled }}
# ArgoCD Application: Grafana
# Sync Wave 1 - After monitoring stack (wave 0)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    path: charts/grafana
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision }}
    helm:
      releaseName: grafana
      valuesObject:
        enabled: true

        global:
          domain: {{ .Values.gateway.domain }}
          namespace: monitoring
          gateway:
            name: {{ .Values.gateway.gateway.name }}
            namespace: {{ .Values.gateway.gateway.namespace }}

        # Pass through grafana-specific configuration
        admin:
          user: {{ .Values.monitoring.grafana.admin.user | default "admin" }}
          password: {{ .Values.monitoring.grafana.admin.password | default "admin" }}

        # Use bitnamilegacy image (consistency with monitoring stack)
        image:
          registry: docker.io
          repository: bitnamilegacy/grafana

        resources:
          {{- toYaml .Values.monitoring.grafana.resources | nindent 10 }}

        persistence:
          enabled: {{ .Values.monitoring.grafana.persistence.enabled | default true }}
          size: {{ .Values.monitoring.grafana.persistence.size | default "10Gi" }}
          storageClass: {{ .Values.monitoring.grafana.persistence.storageClass | default "" | quote }}

        gateway:
          enabled: {{ .Values.monitoring.grafana.gateway.enabled | default true }}
          hostname: {{ .Values.monitoring.grafana.gateway.hostname | default "" | quote }}

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m
{{- end }}
