{{- if .Values.monitoring.grafana.enabled }}
# ArgoCD Application: Grafana
# Sync Wave 1 - After monitoring stack (wave 0)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    path: charts/grafana
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision }}
    helm:
      releaseName: grafana
      valuesObject:
        global:
          domain: {{ .Values.gateway.domain }}
          namespace: monitoring
          gateway:
            name: {{ .Values.gateway.gateway.name }}
            namespace: {{ .Values.gateway.gateway.namespace }}
        {{- toYaml .Values.monitoring.grafana | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m
{{- end }}
