{{- if .Values.monitoring.enabled }}
# ArgoCD Application: Monitoring Stack
# Sync Wave 0 - Deploy monitoring (cluster-wide, optional)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Multi-source configuration
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: {{ .Values.monitoring.version | default "56.0.0" }}
      helm:
        releaseName: monitoring
        valueFiles:
          - $values/infrastructure/monitoring/helm-values.yaml
    
    - repoURL: {{ .Values.argocd.repoURL }}
      targetRevision: {{ .Values.argocd.targetRevision }}
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m
  
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
{{- end }}
