# ArgoCD Application: TLS Secrets (SOPS + KSOPS)
# Sync Wave -1 - Deploy secrets before cert-manager ClusterIssuers

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tls-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/name: tls-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision | default "main" }}
    path: infrastructure/tls
    # Use KSOPS Config Management Plugin for SOPS decryption
    plugin:
      name: ksops-v1.0

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # Namespace created by cert-manager
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 2m
