{{- if .Values.velero.enabled }}
# ArgoCD Application: Velero Backup Resources
# Sync Wave 1 - Deploy after Velero operator (wave 0)
# Deploys BackupStorageLocation, VolumeSnapshotLocation, and Backup Schedules

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision }}
    path: infrastructure/velero
    helm:
      releaseName: velero-resources
      valueFiles:
        - ../../../values/infrastructure/main.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: velero

  syncPolicy:
    automated:
      prune: false  # Never auto-delete backup configurations
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # Namespace created by velero operator
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m

  ignoreDifferences:
    - group: velero.io
      kind: BackupStorageLocation
      jsonPointers:
        - /status
    - group: velero.io
      kind: VolumeSnapshotLocation
      jsonPointers:
        - /status
    - group: velero.io
      kind: Schedule
      jsonPointers:
        - /status
{{- end }}
