{{- if .Values.velero.enabled }}
# ArgoCD Application: Velero
# Sync Wave 0 - Deploy backup infrastructure (cluster-wide)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: {{ .Values.velero.version | default "7.1.4" }}
    helm:
      releaseName: velero
      values: |
        configuration:
          defaultBackupTTL: 720h
          defaultVolumesToFsBackup: true
        credentials:
          useSecret: true
          existingSecret: velero-credentials
        deployNodeAgent: true
        nodeAgent:
          podVolumePath: /var/lib/kubelet/pods
          privileged: true
        initContainers:
{{- if or (eq .Values.velero.provider "aws") (eq .Values.velero.provider "digitalocean") (eq .Values.velero.provider "minio") }}
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.10.0
            volumeMounts:
              - mountPath: /target
                name: plugins
{{- end }}
{{- if eq .Values.velero.provider "azure" }}
          - name: velero-plugin-for-microsoft-azure
            image: velero/velero-plugin-for-microsoft-azure:v1.10.0
            volumeMounts:
              - mountPath: /target
                name: plugins
{{- end }}
{{- if eq .Values.velero.provider "gcp" }}
          - name: velero-plugin-for-gcp
            image: velero/velero-plugin-for-gcp:v1.10.0
            volumeMounts:
              - mountPath: /target
                name: plugins
{{- end }}
        serviceAccount:
          server:
            create: true
            name: velero
            annotations:
{{- if eq .Values.velero.provider "aws" }}
              eks.amazonaws.com/role-arn: {{ .Values.velero.aws.roleArn }}
{{- end }}
{{- if eq .Values.velero.provider "azure" }}
              azure.workload.identity/client-id: {{ .Values.velero.azure.identityClientId }}
{{- end }}
{{- if eq .Values.velero.provider "gcp" }}
              iam.gke.io/gcp-service-account: {{ .Values.velero.gcp.serviceAccount }}
{{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: velero

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 5m

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /status
{{- end }}
